In [1]:
import pandas as pd
import numpy as np

In [2]:
client_data = pd.read_csv("U_of_DE_Comp.csv")
client_data.head()

,Acct1,Acct2,Acct3,Acct4,Acct5,Acct6,Acct7,Acct8,Acct9,Acct10,...,line_12m,line_24m,PubRec1,Repo1,Score1,Score2,Util1,Util2,Util3,Util4
0,83,1,2,0,204,1,89,0,1,1,...,1000,1000,0,0,715,689,40,60,40,13
1,83,3,19,0,205,17,96,0,0,0,...,19500,19500,0,0,654,668,73,56,89,9
2,84,9,15,2,123,12,68,0,0,0,...,1000,1000,0,0,627,626,75,76,81,12
3,84,9,16,0,204,25,82,0,0,2,...,11000,11000,0,0,730,722,34,93,17,11
4,83,1,4,0,196,1,100,0,0,2,...,10000,10000,0,0,794,808,5,8,6,8

In [3]:
columns = ["Acct1", "Acct2", "Acct3", "Acct4", "Acct5", "Acct6", "bad_flg_90plus_24m", "consumer_bad_flg_90plus_24m"]
client_data = client_data[columns]
client_data.head()
print("Number of missing values:")
has_missing_or_empty = (client_data.isnull() | (client_data == "")).any().any()
print(has_missing_or_empty.sum())

Number of missing values:
0

In [4]:
client_data.describe()

,Acct1,Acct2,Acct3,Acct4,Acct5,Acct6,bad_flg_90plus_24m,consumer_bad_flg_90plus_24m
count,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000
mean,60.666363,10.751007,8.034900,0.817820,241.567463,5.727093,0.063073,0.091187
std,26.599734,26.130304,8.030728,5.844026,589.592883,7.012475,0.243095,0.287875
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,39.000000,1.000000,3.000000,0.000000,114.000000,2.000000,0.000000,0.000000
50%,73.000000,3.000000,6.000000,0.000000,194.000000,4.000000,0.000000,0.000000
75%,84.000000,5.000000,11.000000,1.000000,289.000000,7.000000,0.000000,0.000000
max,99.000000,99.000000,99.000000,99.000000,9999.000000,99.000000,1.000000,1.000000